name: Check Maccabi Appointment

on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Check appointment
        run: |
          python << 'EOF'
          import requests

          URL = "https://serguide.maccabi4u.co.il/heb/doctors/doctorssearchresults/doctorsinfopage/?ItemKeyIndex=294C0ECEA77D988FD7346AD53BA107CC95DDB7064AD8C42B027B0BC070B5759D&RequestId=00000000-0000-0001-0000-000000000191&Source=undefinedResults"

          r = requests.get(URL, timeout=30)

          print("STATUS:", r.status_code)
          print(r.text[:5000])

          EOF
